### PR TITLE
Persistent cache using SQLite

### PR DESCRIPTION
**Pull request by dhruviyer**
Addresses #42 by replacing `OrderedDict` in `cache.py` with a SQLite DB

### CODE REVIEW

**Comment by sidjha1** [comment]
Thanks for the PR @dhruviyer! Could we also allow for the cache to just be in-memory? Basically it would be nice to give the user some flexibility about the underlying cache storage. I could imagine there is one general `Cache` class and then some sort of `InMemoryCache`, `RedisCache`, `SQLiteCache`, etc. subclass that implements the basic `Cache` operations for all the storage engines.

**Comment by dhruviyer** [comment]
@sidjha1 thanks for the feedback -- agree that it makes sense to support multiple storage engines. I will work on this and mark the PR when ready for review

**Comment by dhruviyer** [comment]
@sidjha1 let me know what you think of these changes:

1. Created `Cache` abstract class with implementations for SQLiteCache and InMemoryCache
2. Factory pattern to abstract away cache creation and uses a new CacheConfig object (also an enum to select among storage engines)
4. Use dependency injection in LM

**Review by sidjha1 — APPROVED** [review]
@dhruviyer LGTM! The CI is failing on the tests that require OAI keys since GH doesn't propagate secrets to actions started by third-party contributors. In any case I don't see this breaking anything. Approved.

**Pull request merged**
